config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get 'api/login'
  post 'api/signup'
  get 'api/rivers'
  get 'api/river'
  get 'api/favorites'
  get 'api/favorite'
  get 'api/alert'
  get 'api/unfavorite'

  # get 'alert/create'
  # get 'alert/destroy'
  get 'relationship/create'
  get 'relationship/destroy'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'home' => "static_pages#home"
  get 'pending' => 'rivers#pending'
  get 'approve'   => 'rivers#approve'



  resources :users
  resources :rivers
  resources :relationship, only: [:create, :destroy]
  resources :alerts
  resources :ads

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @user = current_user
    if logged_in?
      @river = River.new
      @rivers = search params
      if  @user.nil? || @user.favorites.nil?
        @rivers = []
      else
        @rivers = @user.favorites
      end

    end
  end

  def help
  end

  def about
  end

  def search(params)
    River.where("name LIKE (?)","%#{params[:name]}%")
        .where("section LIKE (?)","%#{params[:section]}%")
        .where("difficulty LIKE (?)","%#{params[:difficulty]}%")
        .where("state LIKE (?)","%#{params[:state]}%")
        .where(approved: true)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
 <h3><%= @user.name %></h3>
    <div class="col-md-4">
    <%= render 'rivers/river_form' %>
    </div>
    <div class="col-md-8">
      <h3>Favorite Rivers

      </h3>
      <small class="pull-right col-">
        <%= link_to 'See all rivers', rivers_path %>
      </small>
      <%= render 'rivers/rivers' %>
    </div>
    <%else %>
<div class="jumbotron center">
  <div class="conainter">
    <h1>Welcome to River Tracker</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>
<div class="conainer">
  <div class="center">
    <p>Already have an account?
    <%= link_to "Login", login_path %>
    </p>
  </div>
</div>
<% end %>