config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get 'api/login'
  post 'api/signup'
  get 'api/rivers'
  get 'api/river'
  get 'api/favorites'
  get 'api/favorite'
  get 'api/alert'
  get 'api/unfavorite'

  # get 'alert/create'
  # get 'alert/destroy'
  get 'relationship/create'
  get 'relationship/destroy'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'home' => "static_pages#home"
  get 'pending' => 'rivers#pending'
  get 'approve'   => 'rivers#approve'



  resources :users
  resources :rivers
  resources :relationship, only: [:create, :destroy]
  resources :alerts
  resources :ads

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rivers
  has_many :active_relationships, class_name:  "Relationship",
           foreign_key: "favoriter_id",
           dependent:   :destroy
  has_many :favorites, through: :active_relationships, source: :favorited


  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    begin
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    rescue
      log_out
    end
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Favorites a river.
  def favorite(id)
    active_relationships.create(favorited_id: id)
  end

  # removes favorite river.
  def remove_favorite(id)
    active_relationships.find_by(favorited_id: id).destroy
  end

  # returns true if user favorites river
  def following?(river)
    favorites.include?(river)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [ :update]
  before_action :admin, only: [:index]
  before_action :admin_or_correct_user, only: [:edit]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:info] = "Please check your email to activate your account."
        redirect_to root_url
      else
        render 'new'
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
         if admin?
           if !params[:role].eql?("Ignore")
           @user.update_attribute(:role ,params[:role])
         end
         end
        redirect_to @user, notice: 'User was successfully updated.'
      else
         render :edit
      end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def admin_or_correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless admin? || current_user?(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmaiton)
    end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this river from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name  %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:"form-control" %>
  </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password , class:"form-control"%>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, class:"form-control" %>
    </div>
    <% if admin? %>
    <div class="field">
      <%= f.label :role %><br>
      <%= select_tag(:role, options_for_select([["Ignore", "Ignore"],["User","User"],["Advertiser","Advertiser"], ["Admin","Admin"]])) %>
      <%= f.password_field :role, class:"form-control" %>
    </div>
    <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>


        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
    <p>Already have an account?
    <%= link_to "Sign in Here", login_path %>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1 class="center">
  <%= @user.name %>
</h1>


<h3 class="center">
  <%= @user.email %>
</h3>
<div class="center">
  <div class="container col-md-6 col-md-offset-3">
  <%= render 'users/form' %>
  </div>
</div>
</div>