config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get 'api/login'
  post 'api/signup'
  get 'api/rivers'
  get 'api/river'
  get 'api/favorites'
  get 'api/favorite'
  get 'api/alert'
  get 'api/unfavorite'

  # get 'alert/create'
  # get 'alert/destroy'
  get 'relationship/create'
  get 'relationship/destroy'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'home' => "static_pages#home"
  get 'pending' => 'rivers#pending'
  get 'approve'   => 'rivers#approve'



  resources :users
  resources :rivers
  resources :relationship, only: [:create, :destroy]
  resources :alerts
  resources :ads

end

app/views/shared/_admin_tools.html.erb
<ul class="dropdown-menu">
  <li><%= link_to "User List", users_path %></li>
  <li><%= link_to "Pending Rivers", pending_path %></li>
  <li><%= link_to "Account Settings", user_path(current_user.id) %></li>
  <li> <%= link_to "Log out", logout_path, method: "delete" %></li>
</ul>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation col-md-10">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_river_form.html.erb
<h3>New River</h3>
<%= form_for(@river, html: {multipart: true}) do |f| %>
  <%=render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :section %>
    <%= f.text_field :section, class: 'form-control' %>

    <%= f.label :difficulty %>
    <%= f.text_field :difficulty, class: 'form-control' %>

    <%= f.label :usgs_id %>
    <%= f.number_field :usgs_id, class: 'form-control' %>

    <%= f.label :state %>
    <%= f.text_field :state, class: 'form-control' %>


    <%= f.label :state %>
    <%= f.text_field :state, class: 'form-control' %>

    <%= f.label :put_in %>
    <%= f.text_field :put_in, class: 'form-control' %>

    <%= f.label :take_out %>
    <%= f.text_field :take_out, class: 'form-control' %>

    <div class="field">
      <%= f.text_area :details, placeholder: "Enter River description" %>
    </div>

    <%= f.submit "Create River", class: "btn btn-primary" %>

<% end %>

app/views/shared/_rivers.html.erb
<%= form_tag('/rivers', method: 'get') do%>
<table class="table ">
  <thead>
  <tr>
    <th>Name</th>
    <th>Section</th>
    <th>Difficulty</th>
    <th>State</th>
    <th colspan="3"></th>
  </tr>
  </thead>
      <tr>

        <td>
          <%= text_field_tag :name, "",:class =>"form-control"  %>
        </td>
        <td>
          <%= text_field_tag(:section, "",:class =>"form-control") %>
        </td>
        <td>
          <%= text_field_tag(:difficulty, "",:class =>"form-control") %>
        </td>
        <td>
          <%= text_field_tag(:state, "",:class =>"form-control") %>
        </td>
        <td colspan="2">
          <%= submit_tag 'Search', :class =>"btn btn-default" %>
        </td>
        <td>
          <%= link_to "Reset", rivers_path , class: "btn btn-default"%>
        </td>
      </tr>
  <tbody>
  <% @rivers.each do |river| %>
      <tr>
        <td><%= river.name %></td>
        <td><%= river.section %></td>
        <td><%= river.difficulty %></td>
        <td><%= river.state %></td>
        <% if admin? %>
            <td><%= link_to 'Edit', edit_river_path(river) %></td>
            <td><%= link_to 'Delete', river, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <% if current_page?(controller: 'static_pages' , action: 'home' ) %>
            <td><%=link_to 'Remove Favorite', relationship_destroy_path(river.id)%> </td>
        <% else %>
            <td><%=link_to 'Favorite', relationship_create_path(river.id)%> </td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>

app/views/shared/_user_tools.html.erb
<ul class="dropdown-menu">
  <li><%= link_to "Settings", user_path(current_user.id) %></li>
  <li> <%= link_to "Log out", logout_path, method: "delete" %></li>
</ul>