config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get 'api/login'
  post 'api/signup'
  get 'api/rivers'
  get 'api/river'
  get 'api/favorites'
  get 'api/favorite'
  get 'api/alert'
  get 'api/unfavorite'

  # get 'alert/create'
  # get 'alert/destroy'
  get 'relationship/create'
  get 'relationship/destroy'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'home' => "static_pages#home"
  get 'pending' => 'rivers#pending'
  get 'approve'   => 'rivers#approve'



  resources :users
  resources :rivers
  resources :relationship, only: [:create, :destroy]
  resources :alerts
  resources :ads

end

app/models/river.rb
class River < ActiveRecord::Base
    belongs_to :user
    has_many :active_relationships, class_name:  "Relationship",
             foreign_key: "favorited_id",
             dependent:   :destroy
    has_many :favoriters, through: :active_relationships, source: :favorited

    mount_uploader :picture, PictureUploader

    validates :name,  presence: true
    validates :section, presence: true
    validates :difficulty, presence: true
    validates :state, length:{is:2}, presence: true
    validate :usgs_validator
    validate  :picture_size

  private
  def usgs_validator
    if (self.usgs_id.strip.length != 0) && (self.usgs_id.length != 8)
      errors.add(:usgs_id, "should either be blank or an 8 digit number")
    end
  end

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/rivers_controller.rb
class RiversController < ApplicationController
  before_action :admin, only: [:destroy, :edit, :pending, :approve]
  before_action :logged_in_user, only: [:create, :destroy, :edit]


  def index
    if !params[:commit].nil?
      @rivers = search params
      if @rivers.nil?
        @rivers = []
      end
    else
      @rivers = River.where(approved: true)
    end
  end

  def show
    @alert = Alert.new
    @river = River.find(params[:id])
    @alerts = Alert.where(river_id: @river.id )
  end

  def create
    @river = River.new(river_params)
    if @river.valid? && @river.save
      redirect_to root_path
    else
      @rivers = River.all
      @user = current_user
      render 'static_pages/home'
    end
  end

  def destroy
    river = River.find(params[:id])
    river.destroy
    respond_to do |format|
      format.html { redirect_to rivers_url, notice: 'River was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def edit
    @river = River.find(params[:id])
  end

  def update
    respond_to do |format|
      @river = River.find(params[:id])
      if @river.update(river_params)
        format.html { redirect_to @river, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @river }
      else
        format.html { render :edit }
        format.json { render json: @river.errors, status: :unprocessable_entity }
      end
    end
  end


  def pending
    get_pending
  end

  def approve
    @river = River.find(params[:format])
    if !@river.nil?
      @river[:approved] = true
      @river.save if @river.valid?
    end
    redirect_to pending_path
  end

  private

  def search(params)
    River.where("name LIKE (?)","%#{params[:name]}%")
        .where("section LIKE (?)","%#{params[:section]}%")
        .where("difficulty LIKE (?)","%#{params[:difficulty]}%")
        .where("state LIKE (?)","%#{params[:state]}%")
        .where(approved: true)
  end

  def get_pending
    @rivers = River.where(approved: false)
    @rivers = [] if @rivers.nil?
  end

  def river_params
    params.require(:river).permit(:name, :section,
                                  :difficulty, :usgs_id, :details, :state,
                                  :put_in, :take_out, :approved, :picture,
                                  :min_cfs, :max_cfs)
  end



end

app/helpers/rivers_helper.rb
module RiversHelper

  def has_alert?(river)
    alerts = Alert.where(river_id: river.id)
    return !alerts.empty?
  end


end

app/views/rivers/_river_form.html.erb
<h3>New River</h3>
<%= form_for(@river, html: {multipart: true}) do |f| %>
  <%=render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :section %>
    <%= f.text_field :section, class: 'form-control' %>

    <%= f.label :difficulty %>
    <%= f.text_field :difficulty, class: 'form-control' %>

    <%= f.label :usgs_id %>
    <%= f.number_field :usgs_id, class: 'form-control' %>

    <%= f.label :state %>
    <%= f.text_field :state, class: 'form-control' %>


    <%= f.label :put_in %>
    <%= f.text_field :put_in, class: 'form-control' %>

    <%= f.label :take_out %>
    <%= f.text_field :take_out, class: 'form-control' %>

    <%= f.label :min_cfs %>
    <%= f.text_field :min_cfs, class: 'form-control' %>

    <%= f.label :max_cfs %>
    <%= f.text_field :max_cfs, class: 'form-control' %>


    <%= f.text_area :details, placeholder: "Enter River description" , class:'form-control'%>

    <div>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' , class:'form-control '%>
    </div>
<div>
  <%= f.submit "Create River", class: "btn btn-primary" %>
</div>

<% end %>

<script>
$('#river_picture').bind('change', function() {
var size_in_megabytes = this.files[0].size/1024/1024;
if (size_in_megabytes > 5) {
alert('Maximum file size is 5MB. Please choose a smaller file.');
}
});
</script>

app/views/rivers/_river_search.html.erb
<%= form_tag('/rivers', method: 'get') do%>
 <tr>

      <td>
        <%= text_field_tag :name, "",:class =>"form-control"  %>
      </td>
      <td>
        <%= text_field_tag(:section, "",:class =>"form-control") %>
      </td>
      <td>
        <%= text_field_tag(:difficulty, "",:class =>"form-control") %>
      </td>
      <td>
        <%= text_field_tag(:state, "",:class =>"form-control") %>
      </td>
    <td colspan="2">
      <%= submit_tag 'Search', :class =>"btn btn-default" %>
    </td>
      <td>
        <%= link_to "Reset", rivers_path , class: "btn btn-default"%>
      </td>
    </tr>
<% end %>

app/views/rivers/_rivers.html.erb
<%= form_tag('/rivers', method: 'get') do%>
<table class="table ">
  <thead>
  <tr>
    <th>Name</th>
    <th>Section</th>
    <th>Difficulty</th>
    <th>State</th>
    <th>Current Level</th>
    <th colspan="3"></th>
  </tr>
  </thead>
      <tr>

        <td>
          <%= text_field_tag :name, "",:class =>"form-control"  %>
        </td>
        <td>
          <%= text_field_tag(:section, "",:class =>"form-control") %>
        </td>
        <td>
          <%= text_field_tag(:difficulty, "",:class =>"form-control") %>
        </td>
        <td>
          <%= text_field_tag(:state, "",:class =>"form-control") %>
        </td>
        <td colspan="1"></td>
        <td colspan="2">
          <%= submit_tag 'Search', :class =>"btn btn-default" %>
        </td>
        <td>
          <%= link_to "Reset", rivers_path , class: "btn btn-default"%>
        </td>
      </tr>
  <tbody>
  <% @rivers.each do |river| %>
      <tr>
        <td><%= link_to river.name , river_path(river) %></td>
        <td><%= link_to river.section , river_path(river)%></td>
        <td><%= river.difficulty %></td>
        <td><%= river.state %></td>
        <td><%= river.cfs %></td>
        <% if has_alert? river %>
            <td> ALERT!!!</td>
        <% end %>
        <% if admin? %>
            <td><%= link_to 'Edit', edit_river_path(river) %></td>
            <td><%= link_to 'Delete', river, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <% if current_page?(controller: 'static_pages' , action: 'home' ) %>
            <td><%=link_to 'Remove Favorite', relationship_destroy_path(river.id)%> </td>
        <% else %>
            <td><%=link_to 'Favorite', relationship_create_path(river.id)%> </td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>

app/views/rivers/edit.html.erb
<h3 class="center"> Edit <%= @river.section %> section of the <%= @river.name %></h3>
<div class="col-md-6 col-md-offset-3">
  <%= form_for(@river, html: {multipart: true}) do |f| %>
    <% if @river.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@river.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @river.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :section %><br>
      <%= f.text_field :section, class: 'form-control' %>

      <%= f.label :difficulty %>
      <%= f.text_field :difficulty, class: 'form-control' %>

      <%= f.label :usgs_id %>
      <%= f.number_field :usgs_id, class: 'form-control' %>

      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>

      <%= f.label :put_in %>
      <%= f.text_field :put_in, class: 'form-control' %>

      <%= f.label :take_out %>
      <%= f.text_field :take_out, class: 'form-control' %>

      <%= f.label :min_cfs %>
      <%= f.text_field :min_cfs, class: 'form-control' %>

      <%= f.label :max_cfs %>
      <%= f.text_field :max_cfs, class: 'form-control' %>

      <%= f.text_area :details, placeholder: "Enter River description" , class:'form-control'%>

      <%= f.label :approved %>
      <%= f.check_box :approved , class:'left-align' %>
    <div class="actions">
      <%= f.submit  %>
    </div>
      <div>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </div>
<% end %>
</div>

app/views/rivers/index.html.erb
<h3> Rivers </h3>
<%= link_to "add a river", root_path %>

<%= render 'rivers/rivers' %>

app/views/rivers/pending.html.erb
<div class="container">
  <h1>Pending Rivers</h1>
<%= form_tag('/rivers', method: 'get') do%>
    <table class="table container ">
      <thead>
      <tr>
        <th>Name</th>
        <th>Section</th>
        <th>Difficulty</th>
        <th>State</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @rivers.each do |river| %>
          <tr>
            <td><%= river.name %></td>
            <td><%= river.section %></td>
            <td><%= river.difficulty %></td>
            <td><%= river.state %></td>
            <% if admin? %>
                <td><%= link_to "Approve",  approve_path(river) %></td>
                <td><%= link_to 'Delete', river, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>
</div>

app/views/rivers/show.html.erb
<div class="jumbotron river-image" style="background:url(<%= @river.picture.url%>);  background-size:100%;">

  <div class="river-image-title-container">
    <h2 class="river-image-title">
      <%= @river.section %>
    </h2>

    <h2 class="center river-image-subtitle">
      <%= @river.name %>
      <%= @river.difficulty %>
    </h2>
  </div>
</div>
<p>
  Max CFS: <%= @river.max_cfs %>
</p>
<p>
  Min CFS: <%= @river.min_cfs %>
</p>
<p>
  <%= @river.details %>
</p>
<h1>Alerts</h1>
<% @alerts.each do |alert| %>
<h3><%= alert.title %></h3>
   <p> <%= alert.details %></p>
    <p><%= alert.created_at %></p>
<% end %>
<%= render 'alerts/new_alert' %>

<% if admin? %>
    <%= link_to 'Edit', edit_river_path(@river) %> |
<% end %>
<%= link_to 'Back', rivers_path %>